name: Deploy frontend

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build docker image
        run: docker build -t dilacraft/pomotask-frontend:latest -f ./Dockerfile ./

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push image to Docker Hub
        run: docker image push dilacraft/pomotask-frontend:latest

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Connect with SSH and deploy
        uses: apleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: | 
            docker-compose -f /root/pomotask/docker-compose.yml pull frontend
            docker-compose -f /root/pomotask/docker-compose.yml stop frontend
            docker-compose -f /root/pomotask/docker-compose.yml up -d frontend